apiVersion: apps/v1
kind: Deployment
metadata:
  name: eks-flask-app
  labels:
    app: eks-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: eks-flask-app
  template:
    metadata:
      labels:
        app: eks-flask-app
    spec:
      containers:
        - name: flask-container
          image: nirav1611/eks-flask-app:latest
          ports:
            - containerPort: 5000
